// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqVhuxaDMVTSEDMY8Y9uiOizE03UP0OU',
    appId: '1:815721883253:web:3c0fe61d9f488e5d39ba3c',
    messagingSenderId: '815721883253',
    projectId: 'canteen-food-app-f21d4',
    authDomain: 'canteen-food-app-f21d4.firebaseapp.com',
    storageBucket: 'canteen-food-app-f21d4.firebasestorage.app',
    measurementId: 'G-0NRKTTRRXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXLkCvi2HbeRutFcf9zTjH4SWUYcVVbA',
    appId: '1:815721883253:android:7afbd44f06f543bf39ba3c',
    messagingSenderId: '815721883253',
    projectId: 'canteen-food-app-f21d4',
    storageBucket: 'canteen-food-app-f21d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAII2vdkifB2jVluxjOcKRaVz6u9tCPwhQ',
    appId: '1:815721883253:ios:8590bfef2aff238539ba3c',
    messagingSenderId: '815721883253',
    projectId: 'canteen-food-app-f21d4',
    storageBucket: 'canteen-food-app-f21d4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAII2vdkifB2jVluxjOcKRaVz6u9tCPwhQ',
    appId: '1:815721883253:ios:8590bfef2aff238539ba3c',
    messagingSenderId: '815721883253',
    projectId: 'canteen-food-app-f21d4',
    storageBucket: 'canteen-food-app-f21d4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvqVhuxaDMVTSEDMY8Y9uiOizE03UP0OU',
    appId: '1:815721883253:web:fdf8d4aa7d8fa11039ba3c',
    messagingSenderId: '815721883253',
    projectId: 'canteen-food-app-f21d4',
    authDomain: 'canteen-food-app-f21d4.firebaseapp.com',
    storageBucket: 'canteen-food-app-f21d4.firebasestorage.app',
    measurementId: 'G-34XGTH8V9E',
  );
}
